### ISSUE TITLE
Petit hic d'animation lors de la sortie de la souris

### ISSUE THREAD

**Issue by oxypomme** [oxypomme/PT19_20#14]
Fichier : `style.css`
Branche : `experimental-animation`

![demo](https://i.imgur.com/ISwIZBM.gif)

**Comment by Wiltoga** [comment]
mdr tu m'assignes pour un problème que tu as généré xD

**Comment by oxypomme** [comment]
ouais mais tu sais comment ça marche dans le détail les anims, pas moi xD
